### It is a Outlier Detection Algorithm
- Extra Tree Regressor is split data without `Gini Index`


In [14]:
import pandas as pd 
import numpy as np 
from sklearn.ensemble import IsolationForest
import warnings
warnings.filterwarnings('ignore')

In [15]:
milk = pd.read_csv('milk.csv',index_col=0)
milk.head()

water  protein  fat  lactose   ash
Animal                                       
HORSE       90.1      2.6  1.0      6.9  0.35
ORANGUTAN   88.5      1.4  3.5      6.0  0.24
MONKEY      88.4      2.2  2.7      6.4  0.18
DONKEY      90.3      1.7  1.4      6.2  0.40
HIPPO       90.4      0.6  4.5      4.4  0.10

In [16]:
iso = IsolationForest(random_state=24, n_estimators=25, contamination=0.05) # contamination is How Much Outlier You Suspect
result = iso.fit_predict(milk)
result

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1, -1, -1])

In [17]:
milk_labled  = milk.copy()
milk_labled['label'] = result
milk_labled[milk_labled['label'] == -1].count().sum()

12

### On RFM DataSet

In [34]:

rfm = pd.read_csv('rfm_data_customer.csv',index_col=0)
rfm.drop(columns='most_recent_visit', inplace=True)
rfm

revenue  number_of_orders  recency_days
customer_id                                         
22086            777                 9           232
2290            1555                16           115
26377            336                 5            43
24650           1189                12            64
12883           1229                12            23
...              ...               ...           ...
3249             998                10            31
6686             771                 8           187
16418           1016                 9           154
9117             678                 7           195
19184           1519                13           113

[39999 rows x 3 columns]

In [38]:
iso = IsolationForest(random_state=24, n_estimators=25, contamination=0.1) # contamination is How Much Outlier You Suspect
result = iso.fit_predict(rfm)
result

array([ 1,  1, -1, ...,  1,  1,  1])

In [39]:
print(np.unique(result, return_counts = True))

rfm_labled  = rfm.copy()
rfm_labled['label'] = result
rfm_labled[rfm_labled['label'] == -1].count().sum()

(array([-1,  1]), array([ 4000, 35999], dtype=int64))


16000

In [37]:
# Experiment can be done
# take supervised learning dataset 
# build model on data with outliers
# build model on data without outlier