# Scaling

ScaledX = X-mean(X) / Std(X)

In [1]:
import numpy as np 

In [2]:
a = np.array([90,34,89,23,50,120,67])
b = np.array([1,3,4,2,5,2,3])

In [3]:
# what is Standard Deviation: it is a measure of Dispersion

In [4]:
ma, mb = a.mean(), b.mean()

In [5]:
sa, sb = a.std(), b.std()

In [19]:
scl_a = (a-ma) / sa
scl_b = (b-mb) / sb

In [20]:
(ma,sa), (scl_a.mean(), scl_a.std())

((67.57142857142857, 31.923377653630677), (7.335402126987641e-17, 1.0))

In [22]:
(mb,sb), (scl_b.mean(), scl_b.std())

((2.857142857142857, 1.2453996981544782), (-8.921435019309294e-17, 1.0))

**scl_a & scl_b values arevknown as Independent Identically Distributed**

In [25]:
scl_a,scl_b   # now values are between -3 to 3

(array([ 0.70257514, -1.05162521,  0.67125013, -1.39620027, -0.55042511,
         1.64232532, -0.0179    ]),
 array([-1.49120227,  0.11470787,  0.91766294, -0.6882472 ,  1.720618  ,
        -0.6882472 ,  0.11470787]))

In [26]:
# Standard Deviation is Not affects by change of origin

# Standard Scaler

**Using StandardScaler()**

In [29]:
from sklearn.preprocessing import StandardScaler
import pandas as pd

In [30]:
scl_std = StandardScaler()
df = pd.DataFrame({'a': a, 'b': b})
scl_std.fit(df)

StandardScaler()

In [33]:
print(scl_std.mean_)
print(ma, mb)

[67.57142857  2.85714286]
67.57142857142857 2.857142857142857


In [34]:
print(scl_std.scale_)
print(sa, sb)

[31.92337765  1.2453997 ]
31.923377653630677 1.2453996981544782


In [35]:
scl_std.transform(df)

array([[ 0.70257514, -1.49120227],
       [-1.05162521,  0.11470787],
       [ 0.67125013,  0.91766294],
       [-1.39620027, -0.6882472 ],
       [-0.55042511,  1.720618  ],
       [ 1.64232532, -0.6882472 ],
       [-0.0179    ,  0.11470787]])

In [36]:
scl_a, scl_b

(array([ 0.70257514, -1.05162521,  0.67125013, -1.39620027, -0.55042511,
         1.64232532, -0.0179    ]),
 array([-1.49120227,  0.11470787,  0.91766294, -0.6882472 ,  1.720618  ,
        -0.6882472 ,  0.11470787]))

# MinMax Scaling

Scaled Value = OriginalValue-Min(Whole Colummn) / Max(Whole Colummn)-Min(Whole Colummn)

In [46]:
a , b

(array([ 90,  34,  89,  23,  50, 120,  67]), array([1, 3, 4, 2, 5, 2, 3]))

In [50]:
mn_a, mn_b, mx_a, mx_b = a.min(), b.min(), a.max(), b.max()
print("Min value of A: ",mn_a,"\nMin value of B: ", mn_b,"\nMax value of A: ", mx_a,"\nMax value of B: ", mx_b)

Min value of A:  23 
Min value of B:  1 
Max value of A:  120 
Max value of B:  5


In [58]:
scl_a = (a-mn_a) / (mx_a - mn_a)
print(scl_a)
print("-------------------------------------")
scl_b = (b-mn_b) / (mx_b - mn_b)
print(scl_b)

[0.69072165 0.11340206 0.68041237 0.         0.27835052 1.
 0.45360825]
-------------------------------------
[0.   0.5  0.75 0.25 1.   0.25 0.5 ]
